import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { simpleGit } from "simple-git";
import { installHook, hookStatus, type HookType } from "./hook.js";
import { DEFAULT_CONFIG } from "./config.js";

/**
 * `commit-roast init` — one-shot onboarding:
 *   1. Install the prepare-commit-msg hook (unless --no-hook).
 *   2. Drop a `COMMIT_CHEATSHEET.md` Conventional Commits reference (unless --no-cheatsheet).
 *   3. Write a project-local `.commit-roastrc` with the chosen persona/model defaults.
 *
 * Existing files/hooks are detected and skipped (clear message) unless --force is passed.
 */
export interface InitOptions {
  cwd?: string;
  /** Skip git hook installation. */
  noHook?: boolean;
  /** Skip dropping COMMIT_CHEATSHEET.md. */
  noCheatsheet?: boolean;
  /** Persona to bake into `.commit-roastrc`. Defaults to built-in default. */
  persona?: string;
  /** Default model to bake into `.commit-roastrc` (optional). */
  model?: string;
  /** Overwrite existing `.commit-roastrc`, cheatsheet, or hook. */
  force?: boolean;
  /** Hook type to install. Defaults to prepare-commit-msg. */
  hookType?: HookType;
}

export interface InitStep {
  name: "rc" | "cheatsheet" | "hook";
  /** "created" | "updated" | "skipped". */
  status: "created" | "updated" | "skipped";
  /** Resolved path of the artifact (or where it would go). */
  path?: string;
  /** Human-readable reason for skipping or other notes. */
  note?: string;
}

export interface InitResult {
  repoRoot: string;
  steps: InitStep[];
  /** Lines suitable for printing as the "next steps" summary. */
  nextSteps: string[];
}

const RC_FILENAME = ".commit-roastrc";
const CHEATSHEET_FILENAME = "COMMIT_CHEATSHEET.md";

async function pathExists(p: string): Promise<boolean> {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

async function findRepoRoot(cwd: string): Promise<string> {
  // Falls back to cwd if not a git repo. The hook step will still surface the
  // real error when it tries to resolve hooksDir, so we don't bail here.
  try {
    const top = (await simpleGit(cwd).revparse(["--show-toplevel"])).trim();
    return top || resolve(cwd);
  } catch {
    return resolve(cwd);
  }
}

export function buildRcContents(persona: string, model?: string): string {
  const cfg: Record<string, unknown> = { persona };
  if (model) cfg.model = model;
  return JSON.stringify(cfg, null, 2) + "\n";
}

/** Exported for tests + so users can regenerate the cheatsheet by hand. */
export function buildCheatsheet(): string {
  return `# Conventional Commits Cheatsheet

Generated by \`commit-roast init\`. Safe to edit, delete, or check in.

## Format

\`\`\`
<type>(<optional scope>): <imperative subject, <= 72 chars>

<optional body — wrap at ~72 cols, explain *why*>

<optional footer(s) — BREAKING CHANGE:, Refs:, Closes #123>
\`\`\`

## Types

| Type       | Use for                                                   |
|------------|-----------------------------------------------------------|
| \`feat\`     | A new user-visible feature                                |
| \`fix\`      | A bug fix                                                 |
| \`docs\`     | Documentation only                                        |
| \`style\`    | Formatting / whitespace; no code change                   |
| \`refactor\` | Code change that's neither a fix nor a feature           |
| \`perf\`     | Performance improvement                                   |
| \`test\`     | Adding or fixing tests                                    |
| \`build\`    | Build system / dependencies                               |
| \`ci\`       | CI configuration                                          |
| \`chore\`    | Maintenance, tooling, anything not user-visible           |
| \`revert\`   | Reverts a previous commit                                 |

## Rules of thumb

- **Imperative mood** — "add", not "added" or "adds".
- **No trailing period** in the subject.
- **Lowercase the type/scope**, capitalize proper nouns in the subject if needed.
- **Body answers "why"**, not "what" — the diff already shows "what".
- **Breaking changes** get a \`!\` after the type/scope and/or a \`BREAKING CHANGE:\` footer.

## Good

\`\`\`
feat(parser): support optional trailing commas in arg lists

Old parser bailed on \`f(a, b,)\` which is now legal per the spec
(see RFC 1234). Adds two test cases and bumps the grammar version.
\`\`\`

## Bad

\`\`\`
stuff
\`\`\`

(Don't be \`stuff\`. \`commit-roast\` will be unkind.)
`;
}

export async function runInit(opts: InitOptions = {}): Promise<InitResult> {
  const cwd = opts.cwd ?? process.cwd();
  const repoRoot = await findRepoRoot(cwd);
  await mkdir(repoRoot, { recursive: true });

  const steps: InitStep[] = [];

  // 1. .commit-roastrc
  const rcPath = join(repoRoot, RC_FILENAME);
  const persona = opts.persona?.trim() || DEFAULT_CONFIG.persona;
  const rcContents = buildRcContents(persona, opts.model?.trim());
  if (await pathExists(rcPath)) {
    if (opts.force) {
      await writeFile(rcPath, rcContents);
      steps.push({ name: "rc", status: "updated", path: rcPath });
    } else {
      steps.push({
        name: "rc",
        status: "skipped",
        path: rcPath,
        note: `${RC_FILENAME} already exists (use --force to overwrite)`,
      });
    }
  } else {
    await writeFile(rcPath, rcContents);
    steps.push({ name: "rc", status: "created", path: rcPath });
  }

  // 2. COMMIT_CHEATSHEET.md
  if (opts.noCheatsheet) {
    steps.push({
      name: "cheatsheet",
      status: "skipped",
      note: "--no-cheatsheet",
    });
  } else {
    const cheatPath = join(repoRoot, CHEATSHEET_FILENAME);
    if (await pathExists(cheatPath)) {
      if (opts.force) {
        await writeFile(cheatPath, buildCheatsheet());
        steps.push({ name: "cheatsheet", status: "updated", path: cheatPath });
      } else {
        steps.push({
          name: "cheatsheet",
          status: "skipped",
          path: cheatPath,
          note: `${CHEATSHEET_FILENAME} already exists (use --force to overwrite)`,
        });
      }
    } else {
      await writeFile(cheatPath, buildCheatsheet());
      steps.push({ name: "cheatsheet", status: "created", path: cheatPath });
    }
  }

  // 3. Git hook (delegates to existing installer for one source of truth).
  if (opts.noHook) {
    steps.push({ name: "hook", status: "skipped", note: "--no-hook" });
  } else {
    const hookType: HookType = opts.hookType ?? "prepare-commit-msg";
    try {
      const existing = await hookStatus(cwd);
      const row = existing.find((r) => r.type === hookType);
      if (row?.installed && row.managedByCommitRoast && !opts.force) {
        steps.push({
          name: "hook",
          status: "skipped",
          path: row.path,
          note: "commit-roast hook already installed",
        });
      } else if (row?.installed && !row.managedByCommitRoast && !opts.force) {
        steps.push({
          name: "hook",
          status: "skipped",
          path: row.path,
          note: "existing non-commit-roast hook present (use --force to back it up and replace)",
        });
      } else {
        const installed = await installHook({
          cwd,
          type: hookType,
          force: opts.force,
        });
        steps.push({
          name: "hook",
          status: installed.replaced ? "updated" : "created",
          path: installed.path,
          note: installed.backupPath ? `backed up previous hook to ${installed.backupPath}` : undefined,
        });
      }
    } catch (err) {
      steps.push({
        name: "hook",
        status: "skipped",
        note: err instanceof Error ? err.message : String(err),
      });
    }
  }

  const nextSteps = buildNextSteps(steps, persona);
  return { repoRoot, steps, nextSteps };
}

function buildNextSteps(steps: InitStep[], persona: string): string[] {
  const lines: string[] = [];
  lines.push(`Persona set to '${persona}'. Edit ${RC_FILENAME} to change defaults.`);
  const hook = steps.find((s) => s.name === "hook");
  if (hook?.status === "created" || hook?.status === "updated") {
    lines.push("Hook installed — your next `git commit` will get a grade in the editor.");
  } else if (hook?.status === "skipped") {
    lines.push("Hook not installed. Run `commit-roast hook install` when you're ready.");
  }
  const cheat = steps.find((s) => s.name === "cheatsheet");
  if (cheat?.status === "created" || cheat?.status === "updated") {
    lines.push(`Read ${CHEATSHEET_FILENAME} for the Conventional Commits quick reference.`);
  }
  lines.push("Try `commit-roast --count 5` to roast your recent history.");
  if (!process.env.ROAST_API_KEY) {
    lines.push("Set ROAST_API_KEY (+ optionally ROAST_API_BASE/ROAST_MODEL) for real AI roasts.");
  }
  return lines;
}

export function renderInitResult(result: InitResult): string {
  const lines: string[] = [];
  lines.push(`commit-roast init in ${result.repoRoot}`);
  for (const step of result.steps) {
    const label = step.name.padEnd(10);
    const status = step.status.padEnd(8);
    const path = step.path ? ` ${step.path}` : "";
    const note = step.note ? `  (${step.note})` : "";
    lines.push(`  ${label} ${status}${path}${note}`);
  }
  lines.push("");
  lines.push("Next steps:");
  for (const n of result.nextSteps) lines.push(`  - ${n}`);
  return lines.join("\n");
}
